application: puzzlebuddy
version: 20140111092503
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "3600d"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /static/(.*)
  static_files: static/\1
  upload: static/compiled/20140111092503/(.*)
  secure: always

- url: /
  script: main.app
  secure: always

- url: /credentials
  script: main.app
  secure: always
  login: admin

- url: .*
  script: main.app
  secure: always
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
